-- Gestion de colis - Script de creation de la base de donnees PostgreSQL


-- Table : agence
CREATE TABLE agence (
    id_agence   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(100) NOT NULL,
    ville       VARCHAR(150) NOT NULL,
    telephone   VARCHAR(30)  NOT NULL UNIQUE
);


-- Table : client (expéditeur)
CREATE TABLE client (
    id_client   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(100) NOT NULL,
    prenom      VARCHAR(150) NOT NULL,
    telephone   VARCHAR(30)  NOT NULL UNIQUE
);


-- Table : destinataire
CREATE TABLE destinataire (
    id_destinataire   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom               VARCHAR(100) NOT NULL,
    prenom            VARCHAR(100) NOT NULL,
    telephone         VARCHAR(100) NOT NULL UNIQUE
);


-- Table : colis
CREATE TABLE colis (
    id_colis         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_suivi     VARCHAR(30)   NOT NULL UNIQUE,
    code_retrait     VARCHAR(6)    NOT NULL,
    description      VARCHAR(100)  NOT NULL,
    poids            REAL          NOT NULL,
    longueur         REAL          NOT NULL,
    largeur          REAL          NOT NULL,
    hauteur          REAL          NOT NULL,
    valeur_declare   BIGINT        NOT NULL,
    statut           VARCHAR(100)  NOT NULL
        CHECK (statut IN ('ENREGISTRE', 'PRISE_EN_CHARGE', 'EN_TRANSIT', 'ARRIVE_AGENCE', 'LIVRE')),
    date_creation    TIMESTAMP(6)  NOT NULL
);

-- Table : expedition
-- Relie un colis (1-1) à son expéditeur, son destinataire et ses deux agences.
CREATE TABLE expedition (
    id_expedition       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_expedition      TIMESTAMP(6) NOT NULL,
    id_client            BIGINT  NOT NULL REFERENCES client(id_client),
    id_destinataire       BIGINT  NOT NULL REFERENCES destinataire(id_destinataire),
    id_agence_depart      INTEGER NOT NULL REFERENCES agence(id_agence),
    id_agence_arrivee     INTEGER NOT NULL REFERENCES agence(id_agence),
    id_colis              BIGINT  NOT NULL UNIQUE REFERENCES colis(id_colis)
);


-- Table : suivi_colis
-- Historique (append-only) des changements de statut d'un colis.
CREATE TABLE suivi_colis (
    id_suivi        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_colis        BIGINT        NOT NULL REFERENCES colis(id_colis),
    statut          VARCHAR(255)  NOT NULL
        CHECK (statut IN ('ENREGISTRE', 'PRISE_EN_CHARGE', 'EN_TRANSIT', 'ARRIVE_AGENCE', 'LIVRE')),
    date_statut     TIMESTAMP(6)  NOT NULL,
    commentaire     VARCHAR(255)  NOT NULL
);

-- Index utile pour l'historique (lecture triee par date pour un colis donne)
CREATE INDEX idx_suivi_colis_id_colis ON suivi_colis (id_colis, date_statut);
